version: 2.1

executors:
  dotnet8:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022
    working_directory: ~/samples.xunit

jobs:
  build-and-test:
    executor: dotnet8
    steps:
      - checkout

      - run:
          name: Show .NET SDK version
          command: dotnet --info

      - run:
          name: Restore packages
          command: dotnet restore v3/Samples.v3.sln

      - run:
          name: Build solution
          command: dotnet build v3/Samples.v3.sln --no-restore --configuration Release

      - run:
          name: Run tests
          command: dotnet test v3/Samples.v3.sln --no-build --configuration Release --nologo

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
