version: 2.1

jobs:
  restore:
    docker:
      - image: ubuntu:22.04
    working_directory: ~/samples.xunit
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            apt-get update
            apt-get install -y wget apt-transport-https software-properties-common

      - run:
          name: Add Microsoft package repository
          command: |
            wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            apt-get update

      - run:
          name: Install .NET SDK 9.0
          command: |
            apt-get install -y dotnet-sdk-9.0

      - run:
          name: Show .NET version
          command: dotnet --info

      - run:
          name: Restore NuGet packages
          command: dotnet restore v3/Samples.v3.sln

workflows:
  version: 2
  build:
    jobs:
      - restore
