version: 2.1

jobs:
  say-hello:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Restore NuGet packages
          command: dotnet restore

workflows:
  say-hello-workflow:
    jobs:
      - say-hello